import React, { useMemo } from "react";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "../ui/sheet";
import { Button } from "../ui/button";
import { Copy, Code as CodeIcon } from "lucide-react";
import { toast } from "sonner";

const buildWebCode = (appName, primaryColor, tagline) => `import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import './App.css';

// ${appName} — generated by BDapps
// Tagline: ${tagline}

const PRIMARY = '${primaryColor}';

function NavBar() {
  return (
    <nav className="flex items-center justify-between px-6 py-4 border-b">
      <a href="/" className="font-bold text-lg" style={{ color: PRIMARY }}>
        ${appName}
      </a>
      <div className="flex items-center gap-5 text-sm text-slate-600">
        <a href="/">Home</a>
        <a href="/features">Features</a>
        <a href="/pricing">Pricing</a>
        <a href="/contact">Contact</a>
      </div>
      <button
        className="px-3 py-2 rounded-md text-white text-xs font-semibold"
        style={{ background: PRIMARY }}
      >
        Get Started
      </button>
    </nav>
  );
}

function Hero() {
  return (
    <section className="px-6 py-12">
      <h1 className="text-4xl font-bold tracking-tight">
        ${tagline}
      </h1>
      <p className="text-slate-500 mt-2">
        Powered by BDapps Platform.
      </p>
    </section>
  );
}

export default function App() {
  return (
    <BrowserRouter>
      <NavBar />
      <Routes>
        <Route path="/" element={<Hero />} />
      </Routes>
    </BrowserRouter>
  );
}`;

const buildAndroidCode = (appName, primaryColor, slogan) => `import 'package:flutter/material.dart';

// ${appName} — generated by BDapps
// Slogan: ${slogan}

const Color kPrimary = Color(0xFF${primaryColor.replace("#", "").toUpperCase()});

void main() => runApp(const ${appName.replace(/[^a-zA-Z]/g, "") || "MyApp"}());

class ${appName.replace(/[^a-zA-Z]/g, "") || "MyApp"} extends StatelessWidget {
  const ${appName.replace(/[^a-zA-Z]/g, "") || "MyApp"}({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${appName}',
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: kPrimary,
      ),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: kPrimary,
        foregroundColor: Colors.white,
        title: const Text('${appName}'),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.bolt, size: 64, color: kPrimary),
              const SizedBox(height: 16),
              Text(
                '${slogan}',
                textAlign: TextAlign.center,
                style: Theme.of(context).textTheme.titleLarge,
              ),
            ],
          ),
        ),
      ),
    );
  }
}`;

// Lightweight syntax highlighter — keyword / string / comment colors
const highlight = (code, lang) => {
  const keywords = lang === "dart"
    ? ["import", "class", "extends", "const", "final", "void", "return", "new", "if", "else", "for", "while", "true", "false", "null", "super", "this", "Widget", "BuildContext", "MaterialApp", "Scaffold", "AppBar", "StatelessWidget", "Color", "ThemeData", "Theme", "runApp"]
    : ["import", "from", "const", "let", "function", "return", "export", "default", "if", "else", "for", "while", "true", "false", "null", "class", "extends", "new", "this"];

  return code.split("\n").map((line, idx) => {
    let l = line;
    // Comments
    if (l.trim().startsWith("//")) {
      return <div key={idx}><span style={{ color: "#6a9955" }}>{l}</span></div>;
    }
    // tokenise by simple regex
    const parts = [];
    let rest = l;
    let safe = 0;
    while (rest && safe < 100) {
      safe += 1;
      // string
      const strMatch = rest.match(/^([^"'`]*?)(["'`])(.*?)\2/);
      if (strMatch) {
        const [, pre, q, body] = strMatch;
        if (pre) parts.push({ t: pre, type: "text" });
        parts.push({ t: `${q}${body}${q}`, type: "string" });
        rest = rest.slice(strMatch[0].length);
        continue;
      }
      parts.push({ t: rest, type: "text" });
      break;
    }
    return (
      <div key={idx}>
        {parts.map((p, i) => {
          if (p.type === "string") return <span key={i} style={{ color: "#ce9178" }}>{p.t}</span>;
          // colorize keywords
          const tokens = p.t.split(/(\b)/);
          return (
            <span key={i}>
              {tokens.map((tk, j) => {
                if (keywords.includes(tk)) return <span key={j} style={{ color: "#569cd6" }}>{tk}</span>;
                return <span key={j} style={{ color: "#d4d4d4" }}>{tk}</span>;
              })}
            </span>
          );
        })}
      </div>
    );
  });
};

const CodeDrawer = ({ open, onClose, type, appName, primaryColor, tagline }) => {
  const code = useMemo(() => (
    type === "web" ? buildWebCode(appName, primaryColor, tagline) : buildAndroidCode(appName, primaryColor, tagline)
  ), [type, appName, primaryColor, tagline]);

  const filename = type === "web" ? "App.jsx" : "main.dart";
  const lang = type === "web" ? "jsx" : "dart";

  const onCopy = () => {
    navigator.clipboard?.writeText(code).catch(() => {});
    toast.success("Copied!");
  };

  return (
    <Sheet open={open} onOpenChange={(o) => !o && onClose()}>
      <SheetContent data-testid="code-drawer" side="right" className="w-full sm:max-w-[600px] p-0 flex flex-col gap-0 bg-[#1e1e1e] border-l-slate-800">
        <SheetHeader className="px-4 py-3 border-b border-slate-700">
          <div className="flex items-center justify-between">
            <SheetTitle className="text-white flex items-center gap-2 text-sm">
              <CodeIcon size={14} className="text-emerald-400" />
              <span className="font-mono">{filename}</span>
              <span className="text-[10px] uppercase tracking-widest text-slate-500 ml-2">{lang}</span>
            </SheetTitle>
            <Button data-testid="code-copy" size="sm" variant="outline" onClick={onCopy} className="bg-transparent text-white border-slate-600 hover:bg-slate-800 h-7 text-xs">
              <Copy size={12} className="mr-1" /> Copy Code
            </Button>
          </div>
          <SheetDescription className="text-slate-400 text-xs">Sample {type === "web" ? "React/JSX" : "Flutter/Dart"} code from your generated project.</SheetDescription>
        </SheetHeader>
        <pre className="flex-1 overflow-auto p-4 font-mono text-xs leading-relaxed">
          {highlight(code, lang)}
        </pre>
      </SheetContent>
    </Sheet>
  );
};

export default CodeDrawer;
